

services:
  # Django Backend
  vivere_backend:
    build: ./backend
    container_name: vivere_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - vivere_network

  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: vivere_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vivere_network
  ngrok:
    image: ngrok/ngrok:latest
    container_name: vivere_ngrok
    depends_on:
      - vivere_backend
    env_file:
      - .env
    command: >
      http --authtoken ${NGROK_AUTHTOKEN} vivere_backend:8000
    ports:
      - "4040:4040"   # optional: exposes ngrok web UI at http://localhost:4040
    networks:
      - vivere_network


networks:
  vivere_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: 