

services:
  # Django Backend
  vivere_backend:
    build: ./backend
    container_name: vivere_backend
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - vivere_network

  # React Frontend (Vite)
  vivere_frontend:
    build: ./frontend
    container_name: vivere_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - vivere_backend
    networks:
      - vivere_network

  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: vivere_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vivere_network

networks:
  vivere_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: 