# Generated by Django 5.0 on 2025-08-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dynamic_pricing", "0007_dphistoricalcompetitorprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pms_source", models.CharField(max_length=255)),
                ("kpi_date", models.DateField()),
                ("metric_type", models.CharField(max_length=255)),
                ("total_units", models.IntegerField(default=0)),
                ("available_units", models.IntegerField(default=0)),
                ("units_reserved", models.IntegerField(default=0)),
                ("total_guests", models.IntegerField(default=0)),
                ("guests_reserved", models.IntegerField(default=0)),
                (
                    "daily_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_bookings", models.IntegerField(default=0)),
                ("total_room_nights", models.IntegerField(default=0)),
                (
                    "occupancy_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "revpar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "adr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        db_column="property_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_performance",
                        to="dynamic_pricing.property",
                    ),
                ),
            ],
            options={
                "db_table": "core_daily_performance",
                "indexes": [
                    models.Index(
                        fields=["property", "kpi_date"],
                        name="core_daily__propert_7c6af4_idx",
                    ),
                    models.Index(
                        fields=["pms_source"], name="core_daily__pms_sou_b1d373_idx"
                    ),
                    models.Index(
                        fields=["metric_type"], name="core_daily__metric__cac9f6_idx"
                    ),
                ],
                "unique_together": {
                    ("property", "pms_source", "kpi_date", "metric_type")
                },
            },
        ),
        migrations.CreateModel(
            name="UnifiedReservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservation_id", models.CharField(max_length=255)),
                ("pms_source", models.CharField(max_length=255)),
                ("pms_hotel_id", models.CharField(max_length=255)),
                ("booking_id", models.CharField(max_length=255)),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("total_guests", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        db_column="property_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="dynamic_pricing.property",
                    ),
                ),
            ],
            options={
                "db_table": "core_unified_reservations",
                "indexes": [
                    models.Index(
                        fields=["reservation_id"], name="core_unifie_reserva_81b065_idx"
                    ),
                    models.Index(
                        fields=["property"], name="core_unifie_propert_409bde_idx"
                    ),
                    models.Index(
                        fields=["pms_source"], name="core_unifie_pms_sou_059b90_idx"
                    ),
                    models.Index(
                        fields=["checkin_date"], name="core_unifie_checkin_ace2f2_idx"
                    ),
                    models.Index(
                        fields=["checkout_date"], name="core_unifie_checkou_90a226_idx"
                    ),
                ],
                "unique_together": {("reservation_id", "property")},
            },
        ),
    ]
