# Generated by Django 5.0 on 2025-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_source', models.CharField(max_length=255)),
                ('kpi_date', models.DateField()),
                ('metric_type', models.CharField(max_length=255)),
                ('total_units', models.IntegerField(default=0)),
                ('available_units', models.IntegerField(default=0)),
                ('units_reserved', models.IntegerField(default=0)),
                ('total_guests', models.IntegerField(default=0)),
                ('guests_reserved', models.IntegerField(default=0)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bookings', models.IntegerField(default=0)),
                ('total_room_nights', models.IntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revpar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_daily_performance',
            },
        ),
        migrations.CreateModel(
            name='UnifiedReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=255)),
                ('pms_source', models.CharField(max_length=255)),
                ('pms_hotel_id', models.CharField(max_length=255)),
                ('booking_id', models.CharField(max_length=255)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('total_guests', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_unified_reservations',
            },
        ),
    ]
