# Generated by Django 5.0 on 2025-11-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyperformance',
            table='daily_performance',
        ),
        migrations.AlterModelTable(
            name='unifiedreservations',
            table='unified_reservations',
        ),
    ]
