# Generated by Django 5.0 on 2025-10-22 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('dynamic_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyperformance',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='unifiedreservations',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dynamic_pricing.property'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['property', 'kpi_date'], name='core.daily__propert_dd8c78_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['pms_source'], name='core.daily__pms_sou_d862c9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['metric_type'], name='core.daily__metric__055c63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyperformance',
            unique_together={('property', 'pms_source', 'kpi_date', 'metric_type')},
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['reservation_id'], name='core.unifie_reserva_249529_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['property'], name='core.unifie_propert_cf2fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['pms_source'], name='core.unifie_pms_sou_b99b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['checkin_date'], name='core.unifie_checkin_5bcdeb_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['checkout_date'], name='core.unifie_checkou_3d05ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedreservations',
            unique_together={('reservation_id', 'property')},
        ),
    ]
