# Generated by Django 5.0 on 2025-09-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('dynamic_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyperformance',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_performance', to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='unifiedreservations',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dynamic_pricing.property'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['property', 'kpi_date'], name='core_daily__propert_7c6af4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['pms_source'], name='core_daily__pms_sou_b1d373_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyperformance',
            index=models.Index(fields=['metric_type'], name='core_daily__metric__cac9f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyperformance',
            unique_together={('property', 'pms_source', 'kpi_date', 'metric_type')},
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['reservation_id'], name='core_unifie_reserva_81b065_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['property'], name='core_unifie_propert_409bde_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['pms_source'], name='core_unifie_pms_sou_059b90_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['checkin_date'], name='core_unifie_checkin_ace2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedreservations',
            index=models.Index(fields=['checkout_date'], name='core_unifie_checkou_90a226_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedreservations',
            unique_together={('reservation_id', 'property')},
        ),
    ]
