# Generated by Django 5.0 on 2025-07-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pms_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pms_hotel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_hotel_url', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, help_text='Street address including building number and street name', max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State, province, or region', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in international format (e.g. +34612345678)', max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('cif', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('hostel', 'Hostel'), ('guesthouse', 'Guesthouse'), ('other', 'Other')], max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('rm_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profiles', models.ManyToManyField(blank=True, related_name='properties', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Management System',
                'verbose_name_plural': 'Property Management Systems',
            },
        ),
        migrations.CreateModel(
            name='DpGeneralSettings',
            fields=[
                ('property_id', models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic_pricing.property')),
                ('base_rate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_base_in_pms', models.BooleanField(blank=True, null=True)),
                ('min_competitors', models.IntegerField(default=2)),
                ('comp_price_calculation', models.CharField(default='min', max_length=255)),
                ('competitor_excluded', models.TextField(blank=True, null=True)),
                ('msp_include_events_weekend_increments', models.BooleanField(default=False)),
                ('future_days_to_price', models.IntegerField(default=365)),
                ('pricing_status', models.CharField(default='offline', max_length=255)),
                ('los_status', models.CharField(default='offline', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Pricing General Settings',
                'verbose_name_plural': 'Dynamic Pricing General Settings',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='pms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.propertymanagementsystem'),
        ),
        migrations.CreateModel(
            name='DpEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('event_name', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'unique_together': {('property_id', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='DpDynamicIncrementsV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_level', models.FloatField()),
                ('lead_time_days', models.IntegerField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Dynamic Increment V2',
                'verbose_name_plural': 'Dynamic Increments V2',
                'unique_together': {('property_id', 'occupancy_level', 'lead_time_days')},
            },
        ),
        migrations.CreateModel(
            name='DpDynamicIncrementsV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=255)),
                ('var_from', models.FloatField()),
                ('var_to', models.FloatField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Dynamic Increment V1',
                'verbose_name_plural': 'Dynamic Increments V1',
                'unique_together': {('property_id', 'var_name', 'var_from', 'var_to')},
            },
        ),
        migrations.CreateModel(
            name='DpLosReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time_days', models.IntegerField()),
                ('occupancy_level', models.CharField(max_length=255)),
                ('los_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'LOS Reduction',
                'verbose_name_plural': 'LOS Reductions',
                'unique_together': {('property_id', 'lead_time_days')},
            },
        ),
        migrations.CreateModel(
            name='DpLosSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('day_of_week', models.CharField(max_length=255)),
                ('num_competitors', models.IntegerField(default=2)),
                ('los_aggregation', models.CharField(default='min', max_length=255)),
                ('valid_until', models.DateField()),
                ('los_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'LOS Setup',
                'verbose_name_plural': 'LOS Setups',
                'unique_together': {('property_id', 'valid_from', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DpMinimumSellingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('manual_alternative_price', models.IntegerField()),
                ('msp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Minimum Selling Price',
                'verbose_name_plural': 'Minimum Selling Prices',
                'unique_together': {('property_id', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='DpOfferIncrements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applied_from_days', models.IntegerField()),
                ('applied_until_days', models.IntegerField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Offer Increment',
                'verbose_name_plural': 'Offer Increments',
                'unique_together': {('property_id', 'valid_from', 'valid_until')},
            },
        ),
        migrations.CreateModel(
            name='DpPropertyCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_id', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to='booking.competitor')),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Property Competitor',
                'verbose_name_plural': 'Property Competitors',
                'unique_together': {('property_id', 'competitor_id')},
            },
        ),
        migrations.CreateModel(
            name='DpRoomRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_id', models.CharField(max_length=255)),
                ('base_rate_id', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Room Rate',
                'verbose_name_plural': 'Room Rates',
                'unique_together': {('property_id', 'rate_id')},
            },
        ),
        migrations.CreateModel(
            name='DpWeekdayIncrements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Weekday Increment',
                'verbose_name_plural': 'Weekday Increments',
                'unique_together': {('property_id', 'weekday')},
            },
        ),
    ]
