# Generated by Django 4.2.7 on 2025-07-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpDynamicIncrementsV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=255)),
                ('var_from', models.FloatField()),
                ('var_to', models.FloatField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Increment V1',
                'verbose_name_plural': 'Dynamic Increments V1',
                'db_table': 'dynamic.dp_dynamic_increments_v1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpDynamicIncrementsV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_level', models.FloatField()),
                ('lead_time_days', models.IntegerField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Increment V2',
                'verbose_name_plural': 'Dynamic Increments V2',
                'db_table': 'dynamic.dp_dynamic_increments_v2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('event_name', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'dynamic.dp_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpLosReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time_days', models.IntegerField()),
                ('occupancy_level', models.CharField(max_length=255)),
                ('los_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LOS Reduction',
                'verbose_name_plural': 'LOS Reductions',
                'db_table': 'dynamic.dp_los_reduction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpLosSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('day_of_week', models.CharField(max_length=255)),
                ('num_competitors', models.IntegerField(default=2)),
                ('los_aggregation', models.CharField(default='min', max_length=255)),
                ('valid_until', models.DateField()),
                ('los_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LOS Setup',
                'verbose_name_plural': 'LOS Setups',
                'db_table': 'dynamic.dp_los_setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpMinimumSellingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('manual_alternative_price', models.IntegerField()),
                ('msp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minimum Selling Price',
                'verbose_name_plural': 'Minimum Selling Prices',
                'db_table': 'dynamic.dp_minimum_selling_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpOfferIncrements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('applied_from_days', models.IntegerField()),
                ('applied_until_days', models.IntegerField()),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer Increment',
                'verbose_name_plural': 'Offer Increments',
                'db_table': 'dynamic.dp_offer_increments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpPropertyCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Competitor',
                'verbose_name_plural': 'Property Competitors',
                'db_table': 'dynamic.dp_property_competitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpRoomRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_id', models.CharField(max_length=255)),
                ('base_rate_id', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Rate',
                'verbose_name_plural': 'Room Rates',
                'db_table': 'dynamic.dp_room_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpWeekdayIncrements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=255)),
                ('increment_type', models.CharField(default='Additional', max_length=255)),
                ('increment_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekday Increment',
                'verbose_name_plural': 'Weekday Increments',
                'db_table': 'dynamic.dp_weekday_increments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pms_name', models.CharField(max_length=255)),
                ('pms_hotel_id', models.CharField(max_length=255)),
                ('spreadsheet_id', models.CharField(max_length=255)),
                ('booking_hotel_url', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('rm_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'dynamic.property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DpGeneralSettings',
            fields=[
                ('property_id', models.OneToOneField(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dynamic_pricing.property')),
                ('base_rate_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_base_in_pms', models.BooleanField(blank=True, null=True)),
                ('min_competitors', models.IntegerField(default=2)),
                ('comp_price_calculation', models.CharField(default='min', max_length=255)),
                ('competitor_excluded', models.TextField(blank=True, null=True)),
                ('msp_include_events_weekend_increments', models.BooleanField(default=False)),
                ('future_days_to_price', models.IntegerField(default=365)),
                ('pricing_status', models.CharField(default='offline', max_length=255)),
                ('los_status', models.CharField(default='offline', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Pricing General Settings',
                'verbose_name_plural': 'Dynamic Pricing General Settings',
                'db_table': 'dynamic.dp_general_settings',
                'managed': False,
            },
        ),
    ]
