# Generated by Django 5.0 on 2025-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Management System',
                'verbose_name_plural': 'Property Management Systems',
                'db_table': 'dynamic.property_management_system',
                'managed': False,
            },
        ),
    ]
