# Generated by Django 5.0 on 2025-10-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='properties', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='dpdynamicincrementsv2',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='competitorcandidate',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', help_text='Property this competitor candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_candidates', to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dphistoricalcompetitorprice',
            name='competitor',
            field=models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='dynamic_pricing.competitor'),
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_reductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dplossetup',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dplossetup',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='minimum_selling_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpofferincrements',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dpofferincrements',
            name='user',
            field=models.ForeignKey(help_text='User who created this offer increment', on_delete=django.db.models.deletion.CASCADE, related_name='offer_increments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dppricechangehistory',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dppricechangehistory',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='price_change_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='competitor_id',
            field=models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.competitor'),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='property_competitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dproomrates',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dproomrates',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overwritepricehistory',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='overwritepricehistory',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='overwrite_price_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='pms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.propertymanagementsystem'),
        ),
        migrations.AddField(
            model_name='unifiedroomsandrates',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', help_text='Internal property ID (unique across all PMSs)', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dpgeneralsettings',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dpdynamicincrementsv2',
            unique_together={('property_id', 'occupancy_category', 'lead_time_category')},
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['property_id', 'status'], name='webapp_back_propert_a87cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['user', 'status'], name='webapp_back_user_id_a1de30_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['status', 'created_at'], name='webapp_back_status_39920c_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['deleted', 'status'], name='webapp_back_deleted_39e5f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorcandidate',
            unique_together={('property_id', 'competitor_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dphistoricalcompetitorprice',
            unique_together={('competitor', 'checkin_date', 'room_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dplosreduction',
            unique_together={('property_id', 'occupancy_category', 'lead_time_category')},
        ),
        migrations.AlterUniqueTogether(
            name='dplossetup',
            unique_together={('property_id', 'valid_from', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='dpminimumsellingprice',
            unique_together={('property_id', 'valid_from')},
        ),
        migrations.AlterUniqueTogether(
            name='dpofferincrements',
            unique_together={('property_id', 'valid_from', 'valid_until')},
        ),
        migrations.AlterUniqueTogether(
            name='dppricechangehistory',
            unique_together={('property_id', 'checkin_date', 'as_of')},
        ),
        migrations.AlterUniqueTogether(
            name='dppropertycompetitor',
            unique_together={('property_id', 'competitor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='dproomrates',
            unique_together={('property_id', 'rate_id')},
        ),
        migrations.AlterUniqueTogether(
            name='overwritepricehistory',
            unique_together={('property_id', 'checkin_date')},
        ),
        migrations.AddIndex(
            model_name='unifiedroomsandrates',
            index=models.Index(fields=['property_id'], name='idx_unified_rooms_prop'),
        ),
        migrations.AddIndex(
            model_name='unifiedroomsandrates',
            index=models.Index(fields=['property_id', 'pms_source'], name='idx_unified_rooms_pms'),
        ),
        migrations.AddIndex(
            model_name='unifiedroomsandrates',
            index=models.Index(fields=['property_id', 'room_id'], name='idx_unified_rooms_room'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedroomsandrates',
            unique_together={('property_id', 'room_id', 'rate_id')},
        ),
    ]
