# Generated by Django 5.0 on 2025-10-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='properties', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='dpdynamicincrementsv2',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='competitorcandidate',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', help_text='Property this competitor candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_candidates', to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_reductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dplossetup',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dplossetup',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_setups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='minimum_selling_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpofferincrements',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dpofferincrements',
            name='user',
            field=models.ForeignKey(help_text='User who created this offer increment', on_delete=django.db.models.deletion.CASCADE, related_name='offer_increments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_competitors', to='dynamic_pricing.competitor'),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='property_competitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dproomrates',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='dproomrates',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overwritepricehistory',
            name='property_id',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property'),
        ),
        migrations.AddField(
            model_name='overwritepricehistory',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='overwrite_price_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='pms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.propertymanagementsystem'),
        ),
        migrations.AddField(
            model_name='dpgeneralsettings',
            name='user',
            field=models.ForeignKey(help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dpdynamicincrementsv2',
            unique_together={('property_id', 'occupancy_category', 'lead_time_category')},
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['property_id', 'status'], name='dynamic_pri_propert_bf3b60_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['user', 'status'], name='dynamic_pri_user_id_d482c1_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['status', 'created_at'], name='dynamic_pri_status_a8765c_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorcandidate',
            index=models.Index(fields=['deleted', 'status'], name='dynamic_pri_deleted_241c4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitorcandidate',
            unique_together={('property_id', 'competitor_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dplosreduction',
            unique_together={('property_id', 'occupancy_category', 'lead_time_category')},
        ),
        migrations.AlterUniqueTogether(
            name='dplossetup',
            unique_together={('property_id', 'valid_from', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='dpminimumsellingprice',
            unique_together={('property_id', 'valid_from')},
        ),
        migrations.AlterUniqueTogether(
            name='dpofferincrements',
            unique_together={('property_id', 'valid_from', 'valid_until')},
        ),
        migrations.AlterUniqueTogether(
            name='dppropertycompetitor',
            unique_together={('property_id', 'competitor')},
        ),
        migrations.AlterUniqueTogether(
            name='dproomrates',
            unique_together={('property_id', 'rate_id')},
        ),
        migrations.AlterUniqueTogether(
            name='overwritepricehistory',
            unique_together={('property_id', 'checkin_date')},
        ),
    ]
