# Generated by Django 5.0 on 2025-07-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
