# Generated by Django 5.0 on 2025-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPriceMV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_id', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('raw_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('cancellation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('max_persons', models.IntegerField(blank=True, null=True)),
                ('min_los', models.IntegerField(blank=True, null=True)),
                ('sold_out_message', models.CharField(blank=True, max_length=500, null=True)),
                ('taking_reservations', models.BooleanField(blank=True, null=True)),
                ('scrape_date', models.DateField(blank=True, null=True)),
                ('is_available', models.IntegerField(blank=True, null=True)),
                ('num_days', models.IntegerField(blank=True, null=True)),
                ('update_tz', models.DateTimeField()),
            ],
            options={
                'db_table': 'comp_prices_mv',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='dphistoricalcompetitorprice',
            table='historical_competitor_prices',
        ),
    ]
