# Generated by Django 5.0 on 2025-09-16 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dpgeneralsettings',
            name='otas_price_diff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dpgeneralsettings',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_reductions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dplossetup',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='los_setups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='minimum_selling_prices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dppricechangehistory',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='price_change_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='property_competitors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dproomrates',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedroomsandrates',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this property', on_delete=django.db.models.deletion.CASCADE, related_name='unified_rooms_and_rates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
