# Generated by Django 5.0 on 2025-07-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0002_alter_property_number_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpminimumsellingprice',
            name='manual_alternative_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
