# Generated by Django 5.0 on 2025-10-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiedroomsandrates',
            name='user',
        ),
    ]
