# Generated by Django 5.0 on 2025-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0003_remove_unifiedroomsandrates_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dplosreduction',
            name='lead_time_category',
            field=models.CharField(choices=[('0-1', '0-1 days'), ('1-3', '1-3 days'), ('3-7', '3-7 days'), ('7-14', '7-14 days'), ('14-30', '14-30 days'), ('30-45', '30-45 days'), ('45-60', '45-60 days'), ('60+', '60+ days')], default='3-7', help_text='Lead time category', max_length=10),
        ),
        migrations.AddField(
            model_name='dplosreduction',
            name='occupancy_category',
            field=models.CharField(choices=[('0-30', '0-30%'), ('30-50', '30-50%'), ('50-70', '50-70%'), ('70-80', '70-80%'), ('80-90', '80-90%'), ('90-100', '90-100%'), ('100+', '100%+')], default='50-70', help_text='Occupancy level category', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dplosreduction',
            unique_together={('property_id', 'occupancy_category', 'lead_time_category')},
        ),
        migrations.RemoveField(
            model_name='dplosreduction',
            name='lead_time_days',
        ),
        migrations.RemoveField(
            model_name='dplosreduction',
            name='occupancy_level',
        ),
    ]
