# Generated by Django 5.0 on 2025-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_competitor_booking_link'),
        ('dynamic_pricing', '0003_alter_dpminimumsellingprice_manual_alternative_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpgeneralsettings',
            name='competitors_excluded',
            field=models.ManyToManyField(blank=True, related_name='properties_excluded', to='booking.competitor'),
        ),
        migrations.AlterField(
            model_name='dpofferincrements',
            name='applied_from_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dpofferincrements',
            name='applied_until_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
