# Generated by Django 5.0 on 2025-10-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0003_competitorpricemv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dproomrates',
            name='increment_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='unifiedroomsandrates',
            table='unified_rooms_and_rates',
        ),
    ]
