# Generated by Django 5.0 on 2025-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0004_dpgeneralsettings_competitors_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpminimumsellingprice',
            name='period_title',
            field=models.CharField(blank=True, help_text='Optional name for this MSP period', max_length=255, null=True),
        ),
    ]
