# Generated by Django 5.0 on 2025-10-08 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0004_alter_dplosreduction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpdynamicincrementsv2',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this dynamic increment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_increments_v2', to=settings.AUTH_USER_MODEL),
        ),
    ]
