# Generated by Django 5.0 on 2025-11-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0004_alter_dproomrates_increment_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overwritepricehistory',
            old_name='property_id',
            new_name='property',
        ),
        migrations.AlterUniqueTogether(
            name='overwritepricehistory',
            unique_together={('property', 'checkin_date')},
        ),
    ]
