# Generated by Django 5.0 on 2025-10-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0005_alter_dpdynamicincrementsv2_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dppricechangehistory',
            name='competitor_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
