# Generated by Django 5.0 on 2025-08-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0005_dpminimumsellingprice_period_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpPriceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_hotel_id', models.CharField(max_length=255)),
                ('checkin_date', models.DateField()),
                ('as_of', models.DateTimeField()),
                ('occupancy', models.FloatField(blank=True, null=True)),
                ('msp', models.IntegerField()),
                ('recom_price', models.IntegerField()),
                ('overwrite_price', models.IntegerField(blank=True, null=True)),
                ('recom_los', models.IntegerField()),
                ('overwrite_los', models.IntegerField(blank=True, null=True)),
                ('base_price', models.IntegerField()),
                ('base_price_choice', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_id', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'Price Change History',
                'verbose_name_plural': 'Price Change Histories',
                'unique_together': {('property_id', 'checkin_date', 'as_of')},
            },
        ),
    ]
