# Generated by Django 5.0 on 2025-08-19 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_competitor_booking_link'),
        ('dynamic_pricing', '0006_dppricechangehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpHistoricalCompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('raw_price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('cancellation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('max_persons', models.IntegerField(blank=True, null=True)),
                ('min_los', models.IntegerField(blank=True, null=True)),
                ('sold_out_message', models.CharField(blank=True, max_length=500, null=True)),
                ('taking_reservations', models.BooleanField(blank=True, null=True)),
                ('scrape_date', models.DateField()),
                ('is_available', models.IntegerField(blank=True, null=True)),
                ('num_days', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('update_tz', models.DateTimeField()),
                ('competitor', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='booking.competitor')),
            ],
            options={
                'verbose_name': 'Historical Competitor Price',
                'verbose_name_plural': 'Historical Competitor Prices',
                'unique_together': {('competitor', 'checkin_date', 'room_name')},
            },
        ),
    ]
