# Generated by Django 5.0 on 2025-09-04 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0007_dphistoricalcompetitorprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dppropertycompetitor',
            name='only_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompetitorCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(help_text='Name of the competitor hotel', max_length=255)),
                ('booking_link', models.URLField(blank=True, help_text='Booking.com URL for the competitor', null=True)),
                ('suggested_by_user', models.BooleanField(default=False, help_text='Whether this competitor was suggested by the user')),
                ('similarity_score', models.FloatField(blank=True, help_text='AI-generated similarity score (0.0 to 1.0)', null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('finished', 'Finished'), ('error', 'Error')], default='processing', help_text='Current processing status of this competitor candidate', max_length=20)),
                ('only_follow', models.BooleanField(default=False, help_text='Whether to only follow this competitor without creating a full competitor record')),
                ('deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the candidate was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Error message if status is 'error'", null=True)),
                ('property_instance', models.ForeignKey(db_column='property_id', help_text='Property this competitor candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_candidates', to='dynamic_pricing.property')),
                ('user', models.ForeignKey(help_text='User who suggested or is processing this competitor', on_delete=django.db.models.deletion.CASCADE, related_name='competitor_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competitor Candidate',
                'verbose_name_plural': 'Competitor Candidates',
                'indexes': [models.Index(fields=['property_instance', 'status'], name='dynamic_pri_propert_bf3b60_idx'), models.Index(fields=['user', 'status'], name='dynamic_pri_user_id_d482c1_idx'), models.Index(fields=['status', 'created_at'], name='dynamic_pri_status_a8765c_idx'), models.Index(fields=['deleted', 'status'], name='dynamic_pri_deleted_241c4a_idx')],
                'unique_together': {('property_instance', 'competitor_name')},
            },
        ),
    ]
