# Generated by Django 5.0 on 2025-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('los_message', models.CharField(blank=True, max_length=500, null=True)),
                ('min_los', models.IntegerField(blank=True, null=True)),
                ('sold_out_message', models.CharField(blank=True, max_length=500, null=True)),
                ('b_id', models.IntegerField()),
                ('b_roomtype_id', models.IntegerField()),
                ('b_name', models.CharField(max_length=255)),
                ('b_has_room_inventory', models.BooleanField()),
                ('b_blocks_b_block_id', models.CharField(max_length=255)),
                ('b_blocks_b_raw_price', models.FloatField()),
                ('b_blocks_b_mealplan_included_name', models.CharField(blank=True, max_length=255, null=True)),
                ('b_blocks_b_cancellation_type', models.CharField(max_length=255)),
                ('b_blocks_b_max_persons', models.IntegerField()),
                ('b_blocks_b_price', models.CharField(max_length=255)),
                ('b_blocks_b_rate_is_genius', models.BooleanField()),
                ('b_blocks_b_nr_stays', models.IntegerField()),
                ('b_blocks_b_price_breakdown_simplified_b_excluded_charges_amount', models.FloatField(blank=True, null=True)),
                ('b_blocks_b_price_breakdown_simplified_b_tax_exception', models.FloatField(blank=True, null=True)),
                ('b_blocks_b_price_breakdown_simplified_b_strikethrough_price_amount', models.FloatField(blank=True, db_column='b_strike_price_amt', null=True)),
                ('b_blocks_b_book_now_pay_later', models.BooleanField(blank=True, null=True)),
                ('b_blocks_b_price_breakdown_simplified_b_headline_price_amount', models.FloatField(db_column='b_headline_price_amt')),
                ('b_blocks_b_price_breakdown_simplified_b_vm_products', models.JSONField(blank=True, db_column='b_vm_products', default=list)),
                ('b_blocks_b_price_breakdown_simplified_b_reward_credit_amount', models.FloatField(blank=True, db_column='b_reward_credit_amt', null=True)),
                ('b_blocks_b_stay_prices_b_price', models.CharField(max_length=255)),
                ('b_blocks_b_stay_prices_b_local_price', models.FloatField()),
                ('b_blocks_b_stay_prices_b_raw_price', models.FloatField(blank=True, null=True)),
                ('b_blocks_b_stay_prices_b_stays', models.IntegerField()),
                ('b_blocks_b_stay_prices_b_price_per_night', models.CharField(max_length=255)),
                ('as_of', models.DateTimeField()),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'booking.price_history',
                'managed': True,
                'unique_together': {('hotel_id', 'checkin_date', 'checkout_date', 'b_id', 'b_roomtype_id', 'b_blocks_b_block_id', 'b_blocks_b_cancellation_type', 'b_blocks_b_stay_prices_b_stays', 'as_of')},
            },
        ),
    ]
