# Generated by Django 5.0 on 2025-10-24 17:01

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stripe_session_id', models.CharField(default='', max_length=255, unique=True)),
                ('amount_total', models.IntegerField(default=0, help_text='Stripe gives cents (e.g. 30000 = $300.00)')),
                ('currency', models.CharField(default='', max_length=10)),
                ('payment_status', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('invoice_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_payment',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_profile_picture)),
                ('receive_updates', models.BooleanField(default=False, help_text='Whether the user wants to receive email updates')),
                ('dni', models.CharField(blank=True, help_text='Spanish National Identity Document', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number with country code', max_length=20)),
                ('selected_plan', models.CharField(blank=True, help_text='The plan selected by the user during onboarding', max_length=50, null=True)),
                ('onboarding_step', models.CharField(choices=[('register', 'Register'), ('verify_email', 'Verify Email'), ('hotel_information', 'Hotel Information'), ('pms_integration', 'PMS Integration'), ('select_plan', 'Select Plan'), ('payment', 'Payment'), ('add_competitor', 'Add Competitor'), ('msp', 'MSP'), ('complete', 'Complete')], default='register', help_text='Current step in the onboarding process', max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether the user has completed the onboarding process')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_profile',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for verification', max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='User account (null for anonymous verification)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_emailverificationcode',
                'indexes': [models.Index(fields=['email', 'created_at'], name='profiles_em_email_0994ec_idx'), models.Index(fields=['user', 'created_at'], name='profiles_em_user_id_0daad8_idx'), models.Index(fields=['expires_at'], name='profiles_em_expires_7b2cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error')], default='info', help_text='Type of notification (success, warning, info, error)', max_length=20)),
                ('category', models.CharField(choices=[('pms', 'PMS Integration'), ('pricing', 'Pricing'), ('payment', 'Payment'), ('profile', 'Profile'), ('competitor', 'Competitor'), ('system', 'System'), ('general', 'General')], default='general', help_text='Category of the notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_new', models.BooleanField(default=True, help_text='Whether the notification is new (unacknowledged)')),
                ('action_url', models.CharField(blank=True, help_text='Optional URL for notification action', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp for time-sensitive notifications', null=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'profiles_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='profiles_no_user_id_3b8e17_idx'), models.Index(fields=['user', 'is_new'], name='profiles_no_user_id_5ed63f_idx'), models.Index(fields=['user', 'category'], name='profiles_no_user_id_49c644_idx'), models.Index(fields=['created_at'], name='profiles_no_created_9243ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=100, unique=True)),
                ('invoice_date', models.DateField(help_text='Date when invoice was created')),
                ('pdf_file', models.FileField(help_text='PDF invoice document', upload_to='invoices/%Y/%m/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, help_text='Optional relationship to Stripe payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='profiles.payment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'profiles_invoice',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['user', 'invoice_date'], name='profiles_in_user_id_e50c4b_idx'), models.Index(fields=['invoice_number'], name='profiles_in_invoice_ce32d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PMSIntegrationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('integrated', 'Integrated'), ('not_supported', 'Not Supported'), ('no_pms', 'No PMS')], default='requested', max_length=20)),
                ('custom_pms_name', models.CharField(blank=True, help_text="Custom PMS name when 'other' is selected", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pms_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.propertymanagementsystem')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_integrations', to='dynamic_pricing.property')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_integrations', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'PMS Integration Requirement',
                'verbose_name_plural': 'PMS Integration Requirements',
                'db_table': 'profiles_pmsintegrationrequirement',
                'unique_together': {('property_obj', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('general_question', 'General Question'), ('technical_issue', 'Technical Issue'), ('billing_question', 'Billing Question'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report')], default='general_question', max_length=20)),
                ('title', models.CharField(help_text='Brief title for the support ticket', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot of the issue', null=True, upload_to='support_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'profiles_supportticket',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='profiles_su_user_id_859093_idx'), models.Index(fields=['created_at'], name='profiles_su_created_78828e_idx')],
            },
        ),
    ]
