# Generated by Django 5.0 on 2025-09-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('general_question', 'General Question'), ('technical_issue', 'Technical Issue'), ('billing_question', 'Billing Question'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report')], default='general_question', max_length=20)),
                ('title', models.CharField(help_text='Brief title for the support ticket', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot of the issue', null=True, upload_to='support_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='profiles_su_user_id_859093_idx'), models.Index(fields=['status', 'priority'], name='profiles_su_status_a4f37f_idx'), models.Index(fields=['created_at'], name='profiles_su_created_78828e_idx')],
            },
        ),
    ]
