# Generated by Django 5.0 on 2025-10-08 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('error', 'Error')], default='info', help_text='Type of notification (success, warning, info, error)', max_length=20)),
                ('category', models.CharField(choices=[('pms', 'PMS Integration'), ('pricing', 'Pricing'), ('payment', 'Payment'), ('profile', 'Profile'), ('competitor', 'Competitor'), ('system', 'System'), ('general', 'General')], default='general', help_text='Category of the notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the notification')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_new', models.BooleanField(default=True, help_text='Whether the notification is new (unacknowledged)')),
                ('action_url', models.CharField(blank=True, help_text='Optional URL for notification action', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp for time-sensitive notifications', null=True)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='profiles_no_user_id_3b8e17_idx'), models.Index(fields=['user', 'is_new'], name='profiles_no_user_id_5ed63f_idx'), models.Index(fields=['user', 'category'], name='profiles_no_user_id_49c644_idx'), models.Index(fields=['created_at'], name='profiles_no_created_9243ea_idx')],
            },
        ),
    ]
