# Generated by Django 5.0 on 2025-10-21 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=100, unique=True)),
                ('invoice_date', models.DateField(help_text='Date when invoice was created')),
                ('pdf_file', models.FileField(help_text='PDF invoice document', upload_to='invoices/%Y/%m/')),
                ('payment', models.ForeignKey(blank=True, help_text='Optional relationship to Stripe payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='profiles.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'webapp_backend.profiles_invoice',
                'ordering': ['-invoice_date'],
                'indexes': [models.Index(fields=['user', 'invoice_date'], name='webapp_back_user_id_ef4551_idx'), models.Index(fields=['invoice_number'], name='webapp_back_invoice_b10af9_idx')],
            },
        ),
    ]
