# Generated by Django 5.0 on 2025-07-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMSIntegrationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('integrated', 'Integrated'), ('not_supported', 'Not Supported'), ('no_pms', 'No PMS')], default='requested', max_length=20)),
                ('custom_pms_name', models.CharField(blank=True, help_text="Custom PMS name when 'other' is selected", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pms_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_pricing.propertymanagementsystem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_integrations', to='profiles.profile')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_integrations', to='dynamic_pricing.property')),
            ],
            options={
                'verbose_name': 'PMS Integration Requirement',
                'verbose_name_plural': 'PMS Integration Requirements',
                'unique_together': {('property_obj', 'profile')},
            },
        ),
    ]
