# Generated by Django 5.0 on 2025-08-07 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='alejo@gmail.com', help_text='Email address for verification', max_length=254),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email', 'created_at'], name='email_verif_email_7b81d2_idx'),
        ),
    ]
