# Generated by Django 5.0 on 2025-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_emailverificationcode_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the onboarding process'),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user completed the onboarding process', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_started_at',
            field=models.DateTimeField(blank=True, help_text='When the user started the onboarding process', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_step',
            field=models.CharField(choices=[('register', 'Register'), ('verify_email', 'Verify Email'), ('hotel_information', 'Hotel Information'), ('pms_integration', 'PMS Integration'), ('select_plan', 'Select Plan'), ('payment', 'Payment'), ('add_competitor', 'Add Competitor'), ('msp', 'MSP'), ('complete', 'Complete')], default='register', help_text='Current step in the onboarding process', max_length=20),
        ),
    ]
