# Generated by Django 5.0 on 2025-08-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_started_at',
        ),
    ]
