# Generated by Django 5.0 on 2025-08-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_onboarding_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.CharField(blank=True, help_text='Spanish National Identity Document', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=20),
        ),
    ]
