# Generated by Django 5.0 on 2025-08-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_dni_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_plan',
            field=models.CharField(blank=True, help_text='The plan selected by the user during onboarding', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Payment currency (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('other', 'Other')], help_text='Method used for payment', max_length=20)),
                ('plan_name', models.CharField(help_text='Name of the plan being paid for', max_length=100)),
                ('plan_duration', models.CharField(help_text="Duration of the plan (e.g., 'monthly', 'yearly')", max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID from payment provider', max_length=255, null=True)),
                ('payment_provider', models.CharField(blank=True, help_text="Payment provider name (e.g., 'stripe', 'paypal')", max_length=50, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID', max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID (if recurring)', max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Stripe Invoice ID', max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, help_text='Stripe PaymentMethod ID', max_length=255, null=True)),
                ('stripe_webhook_event_id', models.CharField(blank=True, help_text='Stripe webhook event ID for tracking', max_length=255, null=True)),
                ('stripe_webhook_processed', models.BooleanField(default=False, help_text='Whether the Stripe webhook has been processed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional payment details', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('stripe_metadata', models.JSONField(blank=True, default=dict, help_text='Stripe-specific metadata and response data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='profiles_pa_user_id_d9445a_idx'), models.Index(fields=['status', 'created_at'], name='profiles_pa_status_238fbd_idx'), models.Index(fields=['transaction_id'], name='profiles_pa_transac_5dfc3e_idx'), models.Index(fields=['stripe_payment_intent_id'], name='profiles_pa_stripe__47dc7c_idx'), models.Index(fields=['stripe_customer_id'], name='profiles_pa_stripe__0023ae_idx'), models.Index(fields=['stripe_subscription_id'], name='profiles_pa_stripe__97cb4d_idx'), models.Index(fields=['stripe_webhook_event_id'], name='profiles_pa_stripe__a99d77_idx'), models.Index(fields=['stripe_webhook_processed'], name='profiles_pa_stripe__ac436b_idx')],
            },
        ),
    ]
