# Generated by Django 5.0 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_selected_plan_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_user_id_d9445a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_status_238fbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_transac_5dfc3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_stripe__47dc7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_stripe__0023ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_stripe__97cb4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_stripe__a99d77_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='profiles_pa_stripe__ac436b_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan_duration',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_webhook_event_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_webhook_processed',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
