# Generated by Django 5.0 on 2025-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
