# Generated by Django 5.0 on 2025-08-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_payment_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_total',
            field=models.IntegerField(default=0, help_text='Stripe gives cents (e.g. 30000 = $300.00)'),
        ),
    ]
